name: Update Translations and Wiki Status

on:
  push:
    paths:
      - 'cps/**'
      - 'update_translations.sh'
      - 'compile_translations.sh'
      - 'scripts/generate_translation_status.py'
      - '.github/workflows/update-translations.yml'
  workflow_dispatch:

jobs:
  update-translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install Babel polib

      - name: Run update_translations.sh
        run: bash update_translations.sh

      - name: Clone wiki repo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.wiki.git wiki-tmp
          cp cwa-wiki/Contributing-Translations.md wiki-tmp/Contributing-Translations.md

      - name: Generate translation status table (in wiki repo)
        run: |
          python generate_translation_status.py wiki-tmp/Contributing-Translations.md

      - name: Commit and push wiki update
        run: |
          cd wiki-tmp
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Contributing-Translations.md
          git commit -m "Update translation status table [skip ci]" || echo "No changes to commit"
          git push
